# ===============================================
# Use MiniMessage as text format
#   -> https://docs.advntr.dev/minimessage/format
# ===============================================

chat:
  # Placeholders:
  #   <name> - player name
  #   <message> - message
  message-format: '<name> <yellow>→ <gray><message>'

tab-list:
  # Enable tab list formatting
  enable: true
  # Tab list update period in ticks (20 ticks = 1 second)
  # 0 to disable updating
  update-period: 200
  # Tab list header
  header: '<br><gradient:yellow:gold>Example Server<br>'
  # Tab list footer
  footer: '<br><yellow>Store: <gray>store.example.com<br>'
  # Player name in tab list.
  # <name> - placeholder for player name
  player-name: '<name>'

messages:
  reload: '<green>The <gradient:yellow:gold>BeeChat</gradient> configuration has been reloaded'
