# ===============================================
# Use MiniMessage as text format
#   -> https://docs.advntr.dev/minimessage/format
# ===============================================

chat:
  # Placeholders:
  #   <name> - player name
  #   <message> - message
  message-format: '<name> <yellow>→ <gray><message>'

tab-list:
  enable: true
  update-period: 200
  header: '<br><gradient:yellow:gold>My Server<br>'
  footer: '<br><yellow>Store: <gray>store.my-server.net<br>'
  player-name: '<name>'