# ===============================================
# Use MiniMessage as text format
#   -> https://docs.advntr.dev/minimessage/format
# ===============================================

chat:
  # Placeholders:
  #   <name> - player name
  #   <message> - message
  message-format: '<name> <yellow>→ <gray><message>'
  # Placeholders:
  #   all from `message-format` section
  #   <message_format> - formatted message from `message-format`
  channels:
    # Global chat
    - identifier: '!'
      format: '<message_format>'

    # Staff chat
    - identifier: '#'
      permission: chat.channel.staff
      format: '<red>(Staff)</red> <message_format>'

    # Local chat (40 blocks)
    - distance: 40
      format: '<yellow>(Local)</yellow> <message_format>'

tab-list:
  # Enable tab list formatting
  enable: true
  # Tab list update period in ticks (20 ticks = 1 second)
  # 0 to disable updating
  update-period: 200
  # Tab list header
  header: '<br><gradient:yellow:gold>Example Server<br>'
  # Tab list footer
  footer: '<br><yellow>Store: <gray>store.example.com<br>'
  # Player name in tab list.
  # <name> - placeholder for player name
  player-name: '<name>'

messages:
  # Used when the sender passes an unknown subcommand to the `/beechat` command
  unknown-subcommand: '<red>Unknown subcommand'
  # Message for '/beechat reload' command
  reload: '<green>The <gradient:yellow:gold>BeeChat</gradient> configuration has been reloaded'
