name: BeeChat
main: com.github.beaver010.beechat.BeeChat
version: '1.1'
api-version: '1.20'
authors:
  - beaver010
dependencies:
  server:
    MiniPlaceholders:
      required: false
      load: BEFORE