name: BeeChat
main: com.github.beaver010.beechat.BeeChat
version: '$version'
api-version: '1.21'
authors:
  - beaver010
dependencies:
  server:
    MiniPlaceholders:
      required: false
      load: BEFORE
    PlaceholderAPI:
      required: false
      load: BEFORE
